### ISSUE TITLE
unit test fail : Dispatch_Should_Log_Serialized_Query

### ISSUE THREAD

**Issue by yannickbattail** [Eregrith/Seekyu#2]
Test Name:	Dispatch_Should_Log_Serialized_Query
Test FullName:	Seekyu.Tests.Dispatchers.Delegating.LoggingDispatcherTests.Dispatch_Should_Log_Serialized_Query
Test Source:	C:\Users\Yannick\Downloads\Seekyu\Seekyu.Tests\Dispatchers\Delegating\LoggingDispatcherTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:00,034

Result StackTrace:	
à Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
   à Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
   à Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
   à Moq.Mock`1.Verify(Expression`1 expression, Times times)
   à Moq.Mock`1.Verify(Expression`1 expression, Func`1 times)
   à Seekyu.Tests.Dispatchers.Delegating.LoggingDispatcherTests.Dispatch_Should_Log_Serialized_Query() dans C:\Users\Yannick\Downloads\Seekyu\Seekyu.Tests\Dispatchers\Delegating\LoggingDispatcherTests.cs:ligne 54
Result Message:	
Moq.MockException : 
Expected invocation on the mock once, but was 0 times: m => m.LogQuery("Serialized Query")
No setups configured.

Performed invocations: 
ILogger.LogCommand("Serialized Query")
ILogger.LogResponse(null)

**Comment by Eregrith** [comment]
Fixed by commit b808e6f74a7fe08e88f1481771acad26c2721940

**Comment by yannickbattail** [comment]
all tests are pass.
thanks
